bibentries = c(
  aalen_1978 = bibentry("article",
    author = "Aalen, Odd O and Johansen, Soren",
    journal = "Scandinavian journal of statistics",
    pages = "141--150",
    publisher = "JSTOR",
    title = "An empirical transition matrix for non-homogeneous Markov chains based on censored observations",
    year = "1978"
  ),
  blanche_2013 = bibentry("article",
    author = "Blanche, Paul and Dartigues, Jean Francois and Jacqmin-Gadda, Helene",
    journal = "Statistics in Medicine",
    pages = "5381--5397",
    publisher = "John Wiley & Sons, Ltd",
    title = "Estimating and comparing time-dependent areas under receiver operating characteristic curves for censored event times with competing risks",
    year = "2013",
    doi = "10.1002/SIM.5958",
    issn = "1097-0258",
    month = "December",
    number = "30",
    pmid = "24027076",
    volume = "32",
    url = "https://onlinelibrary.wiley.com/doi/10.1002/sim.5958"
  ),
  
  finegray1999crr = bibentry("article",
     author = "Fine, Jason P. and Gray, Robert J.",
     title = "A proportional hazards model for the subdistribution of a competing risk",
     journal = "Journal of the American Statistical Association",
     volume = 94,
     number = 446,
     year = 1999,
     pages = "496--509"
    ),

  heyard_2020 = bibentry("article",
    author  = "Heyard, Rachel and Timsit, Jean-Francois and Held, Leonhard",
    title   = "Validation of discrete time-to-event prediction models in the presence of competing risks",
    journal = "Biometrical Journal",
    volume  = "62",
    number  = "3",
    pages   = "643--657",
    year    = "2020",
    url     = "https://doi.org/10.1002/BIMJ.201800293"
  ),
  schoop_2011 = bibentry("article",
    author  = "Schoop, Roland and Beyersmann, Jan and Schumacher, Martin and Binder, Harald",
    title   = "Quantifying the predictive accuracy of time-to-event models in the presence of competing risks",
    journal = "Biometrical Journal",
    volume  = "53",
    number  = "1",
    pages   = "88--112",
    year    = "2011",
    url     = "https://doi.org/10.1002/BIMJ.201000073"
  )
)
